version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch:6.5.4
        environment:
            NODE_NAME: example
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            #HTTP_SSl: 'false'
        volumes:
            - /data/elasticsearch:/elasticsearch/data
            - /etc/elasticsearch:/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        network_mode: bridge
        restart: always
